version: 7
layout: post
lang: pt
slug: "settings-language"
type: "interactive"
title: "Configurações de Idioma"
published: true
categories: "mobile"
tags: "mobile"
introduction: Escolha um idioma para o aplicativo.
component: language
action:
  - title: "English"
    language: "en"
    confirmation: "New language applied"
  - title: "Español"
    language: "es"
    confirmation: "Nuevo lenguaje seleccionado"    
  - title: "Français"
    language: "fr"
    confirmation: "Nouveau language selectionné"
  - title: "Português"
    language: "pt"
    confirmation: "Novo idioma aplicado"
