version: 7
layout: post
lang: pt
slug: "settings-message"
type: "interactive"
title: "Configuração de Mensagem de Alerta"
published: true
categories: "mobile"
tags: "mobile"
introduction: Esta é a mensagem que será enviada com a sua localização. 
warning: Combine um plano com seus contatos para que saibam o que fazer quando receberem isto.
component: message
action:
  - title: "Salvar"
    link: "home-ready"
    confirmation: "Mensagem salvo"
