version: 4
layout: post
lang: en
slug: "settings-reset-confirm"
type: "warning"
title: "Confirm the re-installation"
published: true
categories: "mobile"
tags: "mobile"
action:
  - title: "Confirm"
    link: "home-not-configured"
