version: 1
categories: help_using_configuration
toc: ""
module: page_subsection
slug: help_using_configuration_alert_messages
layout: post
lang: en
title: Create your alert message
heading: Create your alert message
published: true
section_order: 2
