version: 7
layout: post
lang: en
slug: "settings-alert"
type: "interactive"
title: "Alert settings"
published: true
categories: "mobile"
tags: "mobile"
introduction: Setup the frequency. 
warning: Be careful about your battery! Sending alerts too often might drain your battery.
component: alert
action:
  - title: "Save"
    link: "home-ready"
    confirmation: "New alert frequency saved"
