version: 1
layout: post
lang: en
slug: "home-not-configured-alarm"
type: "simple"
title: "Panic Button"
published: true
categories: "mobile"
tags: "mobile"
status:
  - title: "Setup not complete"
    color: red
    link: help-not-configured
action:
  - title: "Basic Settings"
    link: ""
    status: checked
  - title: "Setup Alarm"
    link: "setup-alarm"
  - title: "Setup Disguise"
    link: "setup-disguise"
    status: disabled
items:
  -  title: "About"
     link: "setup-about"
  -  title: "Help"
     link: "help"
  -  title: "Language Settings"
     link: "setup-language"
