version: 7
layout: post
lang: en
slug: "settings-code"
type: "interactive"
title: "Create a pincode"
published: true
categories: "mobile"
tags: "mobile"
introduction: This pin code is needed to access the alert settings and to turn the alert messages off. It is not needed to alert contacts in an emergency.
warning: Remember your pincode! If you forget it you will need to reinstall the app.

component: code
action:
  - title: "Save"
    link: "home-ready"
    confirmation: "Pincode saved"
