version: 7
layout: post
lang: en
slug: "settings-message"
type: "interactive"
title: "Setup alert message"
published: true
categories: "mobile"
tags: "mobile"
introduction: This is the message that will be sent with your location. 
warning: Create a plan so your contacts know what to do when they receive this
component: message
action:
  - title: "Save"
    link: "home-ready"
    confirmation: "Message saved"
