version: 1
categories: help_using_configuration
toc: ""
module: page_subsection
slug: help_using_configuration_disguise
layout: post
lang: en
title: Activate disguise
heading: Activate disguise
published: true
section_order: 5
