version: 1
categories: help_using_configuration
toc: ""
module: page_subsection
slug: help_using_configuration_code
layout: post
lang: en
title: Create pin code
heading: Create pin code
published: true
section_order: 3
