version: 7
layout: post
lang: en
slug: "settings-contacts"
type: "interactive"
title: "Setup contacts"
published: true
categories: "mobile"
tags: "mobile"
introduction: These people will receive the alert.
warning: They should know you personally and be able to respond fast.
component: contacts
action:
  - title: "Save"
    link: "home-ready"
    confirmation: "Contacts saved"
