version: 1
layout: post
lang: en
slug: "home-not-configured"
type: simple
title: Panic Button
published: true
categories: mobile
tags: mobile
action: 
  - title: "Set-Up"
    link: "setup-warning"
items: 
  - title: About
    link: "setup-about"
  - title: Language Settings
    link: "setup-language"
