version: 1
categories: help_using_configuration
toc: ""
module: page_subsection
slug: help_using_configuration_contacts
layout: post
lang: en
title: Setting Up Contacts
heading: Setting Up Contacts
published: true
alert: Panic Button is not a replacement for regular contact. Communicate regularly with your network and keep them informed of your planned whereabouts.
section_order: 1
