lang: en
layout: post
title: 'Create your alert message'
module: page_subsection
slug: help_using_configuration_alert_messages
version: 1
published: true
toc: ""
heading: 'Create your alert message'
section_order: 2
categories: help_using_configuration
