K00-version: 1
K01-layout: post
K02-lang: en
K03-slug: home-not-configured
K04-type: simple
K05-title: 'Panic Button'
K06-published: true
K07-categories: mobile
K08-tags: mobile
K09-action:
    -
        K10-title: Set-Up
        K11-link: setup-warning
K12-items:
    -
        K13-title: About
        K14-link: setup-about
    -
        K15-title: 'Language Settings'
        K16-link: setup-language
