lang: en
layout: post
title: 'Activate disguise'
module: page_subsection
slug: help_using_configuration_disguise
version: 1
published: true
toc: ""
heading: 'Activate disguise'
section_order: 5
categories: help_using_configuration
