lang: en
layout: post
tags: mobile
title: 'Confirm the re-installation'
version: 4
published: true
action:
    -
        link: home-not-configured
        title: Confirm
type: warning
slug: settings-reset-confirm
categories: mobile
