lang: en
layout: post
title: 'Setting Up Contacts'
module: page_subsection
slug: help_using_configuration_contacts
version: 1
published: true
toc: ""
alert: 'Panic Button is not a replacement for regular contact. Communicate regularly with your network and keep them informed of your planned whereabouts.'
heading: 'Setting Up Contacts'
section_order: 1
categories: help_using_configuration
